# Generated by Django 4.1.2 on 2023-09-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0004_alter_commentaire_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='image',
        ),
    ]
