# Generated by Django 4.1.2 on 2023-09-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0005_remove_commentaire_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='adresse',
            field=models.CharField(default='ratoma', max_length=20),
        ),
    ]
