# Generated by Django 4.1.2 on 2023-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=120),
        ),
    ]
