# Generated by Django 4.1.2 on 2023-09-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0009_rename_nom_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
