# Generated by Django 4.1.2 on 2023-10-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
