# Generated by Django 4.1.2 on 2023-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0013_remove_cartitem_cart_remove_cartitem_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=128)),
                ('tel', models.PositiveIntegerField()),
            ],
        ),
    ]
