# Generated by Django 4.1.2 on 2023-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduit', '0016_commande_date_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='nom',
            new_name='auteur',
        ),
    ]
